import '../../game_library/domain/game_launch_options.dart';

class Achievement {
  const Achievement(
    this.id,
    this.game,
    this.title,
    this.description,
    this.metric,
    this.target,
    this.emblem,
  );
  final String id;
  final GameKind game;
  final String title;
  final String description;
  final String metric;
  final int target;
  final String emblem;
  int progress(Map<String, int> facts) =>
      (facts['${game.name}:$metric'] ?? 0).clamp(0, target);
  bool earned(Map<String, int> facts) => progress(facts) >= target;
}

/// Stable IDs and specific goals; no timers, daily pressure or purchased rewards.
const achievements = <Achievement>[
  Achievement(
    'scramble_first',
    GameKind.wordScramble,
    'Pieces together',
    'Solve your first scrambled word.',
    'won',
    1,
    'tiles',
  ),
  Achievement(
    'scramble_ten',
    GameKind.wordScramble,
    'Word maker',
    'Build 10 words from shuffled tiles.',
    'won',
    10,
    'pen',
  ),
  Achievement(
    'scramble_fifty',
    GameKind.wordScramble,
    'Master arranger',
    'Build 50 words from shuffled tiles.',
    'won',
    50,
    'crown',
  ),
  Achievement(
    'scramble_unhinted',
    GameKind.wordScramble,
    'Your own way',
    'Solve 10 scrambled words without a hint.',
    'unhinted',
    10,
    'compass',
  ),
  Achievement(
    'scramble_first_check',
    GameKind.wordScramble,
    'Perfect arrangement',
    'Solve 10 words on your first check.',
    'firstCheck',
    10,
    'star',
  ),
  Achievement(
    'scramble_repeated',
    GameKind.wordScramble,
    'Twice as nice',
    'Solve 5 words that contain repeated tiles.',
    'repeated',
    5,
    'link',
  ),
  Achievement(
    'scramble_long',
    GameKind.wordScramble,
    'Big picture',
    'Solve 5 words with at least 6 tiles.',
    'long',
    5,
    'map',
  ),
  Achievement(
    'scramble_english',
    GameKind.wordScramble,
    'English builder',
    'Build 5 English words.',
    'english',
    5,
    'book',
  ),
  Achievement(
    'scramble_roman',
    GameKind.wordScramble,
    'Punjabi builder',
    'Build 5 Romanized Punjabi words.',
    'romanizedPanjabi',
    5,
    'ribbon',
  ),
  Achievement(
    'scramble_gurmukhi',
    GameKind.wordScramble,
    'Gurmukhi builder',
    'Build 5 Gurmukhi words.',
    'gurmukhi',
    5,
    'sun',
  ),
  Achievement(
    'bujho_first',
    GameKind.guessTheWord,
    'First discovery',
    'Solve your first hidden word.',
    'won',
    1,
    'key',
  ),
  Achievement(
    'bujho_five',
    GameKind.guessTheWord,
    'Word detective',
    'Solve 5 hidden words.',
    'won',
    5,
    'search',
  ),
  Achievement(
    'bujho_twentyfive',
    GameKind.guessTheWord,
    'Ink & instinct',
    'Solve 25 hidden words.',
    'won',
    25,
    'book',
  ),
  Achievement(
    'bujho_quick',
    GameKind.guessTheWord,
    'Three strokes',
    'Solve a word in 3 guesses or fewer.',
    'quick',
    1,
    'bolt',
  ),
  Achievement(
    'bujho_firstguess',
    GameKind.guessTheWord,
    'Lucky page',
    'Find a word on your first guess.',
    'firstGuess',
    1,
    'star',
  ),
  Achievement(
    'bujho_streak',
    GameKind.guessTheWord,
    'On a roll',
    'Win 3 rounds in a row in one language and size.',
    'bestStreak',
    3,
    'ribbon',
  ),
  Achievement(
    'bujho_english',
    GameKind.guessTheWord,
    'English ink',
    'Solve an English word.',
    'english',
    1,
    'pen',
  ),
  Achievement(
    'bujho_romanized',
    GameKind.guessTheWord,
    'Punjabi pen',
    'Solve a Romanized Punjabi word.',
    'romanizedPanjabi',
    1,
    'pen',
  ),
  Achievement(
    'bujho_gurmukhi',
    GameKind.guessTheWord,
    'Gurmukhi glow',
    'Solve a Gurmukhi word.',
    'gurmukhi',
    1,
    'sun',
  ),
  Achievement(
    'bujho_sizes',
    GameKind.guessTheWord,
    'Every size',
    'Solve words of 4, 5 and 6 letters.',
    'sizes',
    3,
    'tiles',
  ),
  Achievement(
    'khoj_first',
    GameKind.wordSearch,
    'First expedition',
    'Finish your first word search.',
    'won',
    1,
    'compass',
  ),
  Achievement(
    'khoj_five',
    GameKind.wordSearch,
    'Trail finder',
    'Finish 5 word searches.',
    'won',
    5,
    'map',
  ),
  Achievement(
    'khoj_twentyfive',
    GameKind.wordSearch,
    'Maze master',
    'Finish 25 word searches.',
    'won',
    25,
    'crown',
  ),
  Achievement(
    'khoj_tenwords',
    GameKind.wordSearch,
    'Hidden treasures',
    'Find 10 words in finished puzzles.',
    'words',
    10,
    'key',
  ),
  Achievement(
    'khoj_hundred',
    GameKind.wordSearch,
    'Treasure chest',
    'Find 100 words in finished puzzles.',
    'words',
    100,
    'book',
  ),
  Achievement(
    'khoj_english',
    GameKind.wordSearch,
    'English explorer',
    'Finish an English puzzle.',
    'english',
    1,
    'compass',
  ),
  Achievement(
    'khoj_romanized',
    GameKind.wordSearch,
    'Punjabi pathways',
    'Finish a Romanized Punjabi puzzle.',
    'romanizedPanjabi',
    1,
    'map',
  ),
  Achievement(
    'khoj_gurmukhi',
    GameKind.wordSearch,
    'Script scout',
    'Finish a Gurmukhi puzzle.',
    'gurmukhi',
    1,
    'search',
  ),
  Achievement(
    'khoj_languages',
    GameKind.wordSearch,
    'Three horizons',
    'Finish puzzles in all 3 languages.',
    'languages',
    3,
    'globe',
  ),
  Achievement(
    'khoj_sizes',
    GameKind.wordSearch,
    'Wide horizons',
    'Finish 3 word searches with words of different lengths.',
    'won',
    3,
    'tiles',
  ),
  Achievement(
    'quest_first',
    GameKind.wordQuest,
    'First light',
    'Solve your first Quest word.',
    'won',
    1,
    'lantern',
  ),
  Achievement(
    'quest_five',
    GameKind.wordQuest,
    'Light keeper',
    'Solve 5 Quest words.',
    'won',
    5,
    'sun',
  ),
  Achievement(
    'quest_twentyfive',
    GameKind.wordQuest,
    'Bright mind',
    'Solve 25 Quest words.',
    'won',
    25,
    'crown',
  ),
  Achievement(
    'quest_unhinted',
    GameKind.wordQuest,
    'Your own spark',
    'Solve a Quest word without hints.',
    'unhinted',
    1,
    'bolt',
  ),
  Achievement(
    'quest_tenunhinted',
    GameKind.wordQuest,
    'Steady flame',
    'Solve 10 Quest words without hints.',
    'unhinted',
    10,
    'lantern',
  ),
  Achievement(
    'quest_hinted',
    GameKind.wordQuest,
    'A helping hand',
    'Use a hint and finish the word.',
    'hinted',
    1,
    'hand',
  ),
  Achievement(
    'quest_english',
    GameKind.wordQuest,
    'English spark',
    'Solve an English Quest word.',
    'english',
    1,
    'pen',
  ),
  Achievement(
    'quest_romanized',
    GameKind.wordQuest,
    'Punjabi light',
    'Solve a Romanized Punjabi Quest word.',
    'romanizedPanjabi',
    1,
    'sun',
  ),
  Achievement(
    'quest_gurmukhi',
    GameKind.wordQuest,
    'Script lantern',
    'Solve a Gurmukhi Quest word.',
    'gurmukhi',
    1,
    'lantern',
  ),
  Achievement(
    'quest_sizes',
    GameKind.wordQuest,
    'Light in every fold',
    'Solve Quest words of 4, 5 and 6 letters.',
    'sizes',
    3,
    'tiles',
  ),
  Achievement(
    'jodo_first',
    GameKind.wordBridges,
    'First connection',
    'Finish your first matching set.',
    'won',
    1,
    'bridge',
  ),
  Achievement(
    'jodo_five',
    GameKind.wordBridges,
    'Bridge builder',
    'Finish 5 matching sets.',
    'won',
    5,
    'link',
  ),
  Achievement(
    'jodo_twentyfive',
    GameKind.wordBridges,
    'Word architect',
    'Finish 25 matching sets.',
    'won',
    25,
    'crown',
  ),
  Achievement(
    'jodo_pairs',
    GameKind.wordBridges,
    'Forty connections',
    'Match 40 pairs in finished sets.',
    'words',
    40,
    'tiles',
  ),
  Achievement(
    'jodo_perfect',
    GameKind.wordBridges,
    'A perfect crossing',
    'Finish a set in exactly 4 attempts.',
    'perfect',
    1,
    'star',
  ),
  Achievement(
    'jodo_variety',
    GameKind.wordBridges,
    'New connections',
    'Match 20 distinct words in finished sets.',
    'distinct',
    20,
    'book',
  ),
  Achievement(
    'jodo_english',
    GameKind.wordBridges,
    'English crossing',
    'Finish an English set.',
    'english',
    1,
    'bridge',
  ),
  Achievement(
    'jodo_romanized',
    GameKind.wordBridges,
    'Punjabi crossing',
    'Finish a Romanized Punjabi set.',
    'romanizedPanjabi',
    1,
    'link',
  ),
  Achievement(
    'jodo_gurmukhi',
    GameKind.wordBridges,
    'Script crossing',
    'Finish a Gurmukhi set.',
    'gurmukhi',
    1,
    'bridge',
  ),
  Achievement(
    'jodo_long',
    GameKind.wordBridges,
    'A longer bridge',
    'Finish a set containing a word of at least 5 letters.',
    'long',
    1,
    'map',
  ),
  Achievement(
    'letters_first',
    GameKind.learnLetters,
    'First page',
    'Finish your first letter round.',
    'won',
    1,
    'pen',
  ),
  Achievement(
    'letters_five',
    GameKind.learnLetters,
    'Five pages',
    'Finish 5 letter rounds.',
    'won',
    5,
    'book',
  ),
  Achievement(
    'letters_twentyfive',
    GameKind.learnLetters,
    'Alphabet adventurer',
    'Finish 25 letter rounds.',
    'won',
    25,
    'compass',
  ),
  Achievement(
    'letters_fivefirst',
    GameKind.learnLetters,
    'Sharp eyes',
    'Get 5 first-try answers in finished rounds.',
    'firstTry',
    5,
    'search',
  ),
  Achievement(
    'letters_fiftyfirst',
    GameKind.learnLetters,
    'Letter confidence',
    'Get 50 first-try answers in finished rounds.',
    'firstTry',
    50,
    'ribbon',
  ),
  Achievement(
    'letters_onepracticed',
    GameKind.learnLetters,
    'One to remember',
    'Practice a letter with 3 first-try answers.',
    'practiced',
    1,
    'star',
  ),
  Achievement(
    'letters_tenpracticed',
    GameKind.learnLetters,
    'Letter collection',
    'Reach Practiced for 10 different letters.',
    'practiced',
    10,
    'tiles',
  ),
  Achievement(
    'letters_allpracticed',
    GameKind.learnLetters,
    'All thirty-five',
    'Reach Practiced for all 35 basic letters.',
    'practiced',
    35,
    'crown',
  ),
  Achievement(
    'letters_listen',
    GameKind.learnLetters,
    'Listening ears',
    'Finish a Hear the name, find the letter round.',
    'listening',
    1,
    'ear',
  ),
  Achievement(
    'letters_perfect',
    GameKind.learnLetters,
    'A clean page',
    'Finish a round with all 5 answers right first time.',
    'perfect',
    1,
    'sun',
  ),
];
